#!/usr/bin/env python3

import sys
import requests
from typing import Final

from common.waybar import waybar


DEFAULT_ICON: Final = ""


def weather_icon(condition_code):
    match condition_code:
        case "113":
            return ""  # sunny
        case "116":
            return ""  # partly cloudy
        case "119":
            return ""  # cloudy
        case "122":
            return ""  # very cloudy
        case "143" | "248" | "260":
            return ""  # fog
        case "176" | "263" | "353":
            return ""  # light showers
        case "182" | "185" | "281" | "284" | "311" | "314" | "317" | "350" | "377":
            return ""  # light sleet showers
        case "200" | "386":
            return ""  # thundery showers
        case "227" | "320":
            return ""  # light snow
        case "230" | "329" | "332" | "338":
            return ""  # heavy snow
        case "266" | "293" | "296":
            return ""  # light rain
        case "299" | "305" | "356":
            return ""  # heavy showers
        case "302" | "308" | "359":
            return ""  # heavy rain
        case "323" | "326" | "368":
            return ""  # light snow showers
        case "335" | "371" | "395":
            return ""  # heavy snow showers
        case "389":
            return ""  # thunderstorm with heavy rain
        case "392":
            return ""  # thunderstorm with snow showers
        case _:
            return DEFAULT_ICON  # unknown


try:
    response = requests.get("https://wttr.in?format=j1", timeout=5)
    response.raise_for_status()

    weather = response.json()
    current_condition = weather["current_condition"][0]

    nearest_area = weather["nearest_area"][0]
    region = nearest_area["region"][0]["value"]

    location = f"{region}"


except (requests.RequestException, KeyError, IndexError, ValueError):
    waybar(f"{DEFAULT_ICON} N/A", "Weather unavailable")
    sys.exit(0)

icon = weather_icon(current_condition["weatherCode"])
temp = current_condition["temp_C"]

tooltip = (
    f"{current_condition['weatherDesc'][0]['value']}\n"
    f"Location: {location}\n"
    f"Temperature: {current_condition['temp_C']}°C\n"
    f"Feels like: {current_condition['FeelsLikeC']}°C\n"
    f"Humidity: {current_condition['humidity']}%\n"
    f"Wind: {current_condition['windspeedKmph']} km/h {current_condition['winddir16Point']}\n"
    f"UV Index: {current_condition['uvIndex']}"
)

waybar(f"{icon} {temp}°C", tooltip)
