[main]
font=Inter:size=14,JetBrainsMono Nerd Font Propo:size=14
; font=Inter,JetBrainsMono Nerd Font Propo
horizontal-pad=24
vertical-pad=12
inner-pad=8
icon-theme=Papirus-Dark

[colors]
background=282828ff
text=d4be98ff
prompt=a9b665ff
placeholder=a89984ff
input=ddc7a1ff
match=d8a657ff

selection=45403dff
selection-text=ddc7a1ff
selection-match=d8a657ff

counter=a89984ff
border=d4be98ff

[border]
width=2
radius=8
