return {
  {
    'Senal-D-A-Gunaratna/matugen.nvim',
    lazy = false,
    priority = 1000,
    opts = {
      load_theme = true,

      -- Path to the JSON/JSONC file generated by matugen
      palette_path = '~/.config/matugen/themes/nvim-colors.json',
    },
    config = function(_, opts)
      local function apply_highlights()
        local groups = {
          -- oil
          OilGitAdded = 'GitSignsAdd',
          OilGitModified = 'GitSignsChange',
          OilGitModifiedStaged = 'GitSignsChange',
          OilGitModifiedUnstaged = 'DiagnosticWarn',
          OilGitRenamed = 'Special',
          OilGitDeleted = 'GitSignsDelete',
          OilGitCopied = 'Special',
          OilGitConflict = 'DiagnosticWarn',
          OilGitUntracked = 'DiagnosticHint',
          OilGitIgnored = 'Comment',

          -- dap
          DapBreak = 'DiagnosticError',
          DapStop = 'GitSignsChange',

          -- navic
          NavicIconsFunction = 'GitSignsAdd',
          NavicIconsMethod = 'GitSignsAdd',
          NavicIconsClass = 'DiagnosticInfo',
          NavicText = 'Normal',
          NavicSeparator = 'NonText',
        }

        for group, source in pairs(groups) do
          local source_hl = vim.api.nvim_get_hl(0, { name = source, link = false })
          vim.api.nvim_set_hl(0, group, { fg = source_hl.fg })
        end
      end

      vim.api.nvim_create_autocmd('ColorScheme', {
        group = vim.api.nvim_create_augroup('colorscheme-highlights', { clear = true }),
        pattern = 'matugen',
        callback = apply_highlights,
      })

      require('matugen').setup(opts)
    end,
  },
}
