return {
  'SmiteshP/nvim-navic',
  dependencies = { 'neovim/nvim-lspconfig' },
  opts = {
    depth_limit = 5,
    icons = {
      File = ' ',
      Module = ' ',
      Namespace = ' ',
      Package = ' ',
      Class = ' ',
      Method = ' ',
      Property = ' ',
      Field = '󰜢 ',
      Constructor = ' ',
      Enum = '󰕘 ',
      Interface = '󰕘 ',
      Function = '󰊕 ',
      Variable = ' ',
      Constant = '󰏿 ',
      String = '󰀬 ',
      Number = '󰎠 ',
      Boolean = ' ',
      Array = '󰅪 ',
      Object = '󰅩 ',
      Key = ' ',
      Null = ' ',
      EnumMember = ' ',
      Struct = ' ',
      Event = ' ',
      Operator = '󰆕 ',
      TypeParameter = ' ',
      enabled = true,
    },
    highlight = true,
    lsp = {
      auto_attach = true,
    },
  },
}
