setw -g mode-keys vi
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
setw -g monitor-activity on
set -g bell-action any

set -g status-right '#{prefix_highlight} | %a %B %d, %Y %-I:%M%p'

# key bindings
bind r source-file ~/.config/tmux/tmux.conf \; display-message "reloaded"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind | split-window -h
bind - split-window -v

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

if-shell "test ! -d ~/.config/tmux/plugins/tpm" \
  "run-shell 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm'"

run '~/.config/tmux/plugins/tpm/tpm'
