[config]

[templates.quickshell]
input_path = "./templates/quickshell.json"
output_path = "~/.local/state/quickshell/generated/colors.json"

[templates.niri]
input_path = "./templates/niri.kdl"
output_path = "~/.config/niri/colors.kdl"
post_hook = 'niri msg action load-config-file'

[templates.kitty]
input_path = "./templates/kitty.conf"
output_path = "~/.config/kitty/themes/Matugen.conf"
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.neovim]
input_path = "./templates/nvim.json"
output_path = "~/.config/matugen/themes/nvim-colors.json"
post_hook = "pkill -SIGUSR1 nvim"

[templates.pywalfox]
input_path = "./templates/pywalfox.json"
output_path = "~/.cache/wal/colors.json"
post_hook = 'pywalfox update'

[templates.vesktop]
input_path = "./templates/midnight-discord.css"
output_path = "~/.config/vesktop/themes/midnight-discord.css"

[templates.spotify]
input_path = "./templates/spicetify.ini"
output_path = "~/.config/spicetify/Themes/Sleek/color.ini"
post_hook = "pgrep -x spicetify > /dev/null || spicetify apply -n"
